### ISSUE TITLE
Ping missing

### ISSUE THREAD

**Issue by Kludex** [frankie567/httpx-ws#2]
`ws.ping()`

Very detailed issue. :sunglasses:

**Comment by frankie567** [comment]
Yes!

**Comment by kousikmitra** [comment]
Hi @frankie567 , I have created one PR for this. https://github.com/frankie567/httpx-ws/pull/8

**Comment by frankie567** [comment]
Released in [v0.1.1](https://github.com/frankie567/httpx-ws/releases/tag/v0.1.1)
