### ISSUE TITLE
`anyio.BusyResourceError`: Another task is already writing to this resource

### ISSUE THREAD

**Issue by ZzZombo** [frankie567/httpx-ws#29]
```Traceback (most recent call last):
  File "~~~~.py", line 80, in resolve_url
    await self.ws.send_json(data)
  File "~~~~\Lib\site-packages\httpx_ws\_api.py", line 701, in send_json
    await self.send_text(serialized_data)
  File "~~~~\Lib\site-packages\httpx_ws\_api.py", line 659, in send_text
    await self.send(event)
  File "~~~~\Lib\site-packages\httpx_ws\_api.py", line 638, in send
    await self.stream.write(data)
  File "~~~~\Lib\site-packages\httpcore\backends\asyncio.py", line 51, in write
    await self._stream.send(item=buffer)
  File "~~~~\Lib\site-packages\anyio\_backends\_asyncio.py", line 1291, in send
    with self._send_guard:
  File "~~~~\Lib\site-packages\anyio\_core\_synchronization.py", line 584, in __enter__
    raise BusyResourceError(self.action)
anyio.BusyResourceError: Another task is already writing to this resource
```

I can't quite trace the conditions for the above error, because it only happens occasionally.

**Comment by frankie567** [comment]
Quite hard to tell what's going wrong from this 🤔 Do you try to send several messages concurrently in the same WebSocket?

**Comment by ZzZombo** [comment]
From the output it doesn't seem so. It may appear once in a thousand calls in several hours or several times within a minute. All captured instances had at least ~10ms between calls though. Ironically my admittedly quite crude attempts at fixing it seemed only to severely increase the rate of the error occurring. But question: isn't WS supposed to handle simultaneous messages just fine?

**Comment by Emsu** [comment]
@frankie567 I get this too with audiostreams through websockets in the latest version still.

It looks like it's the background ping writing to the socket at the same time in my case. Sometimes the background ping throws the error and sometime's it's the audio stream data depending on who wrote first and which coroutine got the error.

Is there some way we can make the background ping not cause an error in the userland code?

**Comment by frankie567** [comment]
Hey @T-256 👋  I see you have a fix for this issue. Would you be willing to make a PR for it? :)

**Comment by ncoghlan** [comment]
If you're looking for a reproducing test case, I managed to reliably trigger this exception with the following pattern:

```
    async with client.session() as session:  # <--- This internally creates a httpx-ws websocket session
        def _request_response():
            return session.send_request(**kwds) # <-- This calls `send_json` on the websocket
        requests = [_request_response() for i in range(10)]
        responses = await asyncio.gather(*requests)
```

(it was in a test case I added specifically to test the concurrency support in my own code)

Adding an external `anyio.Lock()` write lock around the application level `ws.send_json()` calls (based on the approach in #89) resolved the problem with that variation, but I suspect it's still vulnerable to the race with the websocket ping writes.

**Comment by GreyElaina** [comment]
> If you're looking for a reproducing test case, I managed to reliably trigger this exception with the following pattern:
> 
> ```
>     async with client.session() as session:  # <--- This internally creates a httpx-ws websocket session
>         def _request_response():
>             return session.send_request(**kwds) # <-- This calls `send_json` on the websocket
>         requests = [_request_response() for i in range(10)]
>         responses = await asyncio.gather(*requests)
> ```
> 
> (it was in a test case I added specifically to test the concurrency support in my own code)
> 
> Adding an external `anyio.Lock()` write lock around the application level `ws.send_json()` calls (based on the approach in #89) resolved the problem with that variation, but I suspect it's still vulnerable to the race with the websocket ping writes (since those aren't guarded by the external lock).

hmm, #89 have covered all the `stream.write` that appears so only one write one time i think. But could you please review #89 and improve that?

**Comment by frankie567** [comment]
Thank you @ncoghlan, that was really helpful 🙏 It helped me to come up with a [test case](https://github.com/frankie567/httpx-ws/pull/89/commits/afe8df9f40b826cdeb842b5872da38f325e4f849) for #89 👍

**Comment by ncoghlan** [comment]
Clarifying my "still vulnerable" comment above: my *external workaround* was vulnerable, since it didn't cover the background ping task. #89 itself looked fine, since it didn't have that problem.
