### ISSUE TITLE
Missing `subprotocols` field in the websocket scope

### ISSUE THREAD

**Issue by YaraslauZhylko** [frankie567/httpx-ws#34]
## Describe the bug

Trying to use `httpx-ws` to test GraphQL subscriptions provided by the `fastapi` + `strawberry` combo using an example from the [Testing ASGI](https://frankie567.github.io/httpx-ws/usage/asgi/) section of the docs.

Establishing WebSocket connection always fails with the following error:
```
self = <httpx_ws.transport.ASGIWebSocketAsyncNetworkStream object at 0x7f0eee7210>

    async def __aenter__(self) -> "ASGIWebSocketAsyncNetworkStream":
        self.exit_stack = contextlib.ExitStack()
        self.portal = self.exit_stack.enter_context(
            anyio.start_blocking_portal("asyncio")
        )
        _: "Future[None]" = self.portal.start_task_soon(self._run)
        await self.send({"type": "websocket.connect"})
        message = await self.receive()
        if message["type"] == "websocket.close":
            await self.aclose()
>           raise WebSocketDisconnect(message["code"], message.get("reason"))
E           httpx_ws._api.WebSocketDisconnect: (<CloseReason.INTERNAL_ERROR: 1011>, "'subprotocols'")

.venv/lib/python3.11/site-packages/httpx_ws/transport.py:53: WebSocketDisconnect
```

Turns out, Strawberry relies on Starletter Websocket `scope` to contain `subprotocols` entry: https://github.com/strawberry-graphql/strawberry/blob/c6eb8656670ba859dd2dd959c9f7a84e6d80ef84/strawberry/fastapi/router.py#L271C6-L271C6
So it fails with a `KeyError("subprotocols")`.

Comparing the scopes generated by `httpx-ws` test transport and the actual queries made by GraphQL clients I found these discrepancies:
![Screenshot_20230628_092307_Termux](https://github.com/frankie567/httpx-ws/assets/1791893/ae905776-310c-4040-9a61-f2406da20964)

So seems like for the real calls, `subprotocols` field is being added to the scopes, while in `httpx-ws` transport it is not: https://github.com/frankie567/httpx-ws/blob/f0e4d4b124d3ca7b0a85178f8294c22542841ce5/httpx_ws/transport.py#L149-L161

Not being a WebSocket guru, I'm not sure if it is actually an `httpx-ws` or `strawberry` bug... :thinking:

## To Reproduce

Test code:
```python
from httpx import AsyncClient
from httpx_ws import aconnect_ws
from httpx_ws.transport import ASGIWebSocketTransport

@pytest.mark.anyio
async def test_subscriptions(fastapi_app):
    async with AsyncClient(transport=ASGIWebSocketTransport(fastapi_app)) as client:
        async with aconnect_ws("ws://test/graphql", client, subprotocols=["graphql-transport-ws"]) as ws:
            pass
```
This raises an error described above.

## Expected behavior

WebSocket connection is expected to be established successfully.

## Potential fix

If I add something like this to the scope creation code in the `httpx-ws` transport:
```python
scope = {
    ...,
    "subprotocols": [subprotocol for subprotocol in headers.get("sec-websocket-protocol", "").split(",") if subprotocol],
}
```
the connection is successful.

## Configuration

 - Python version: 3.11.4
 - httpx-ws version: 0.4.0
 - fastapi version: 0.98.0
 - strawberry-graphql version: 0.190.0

**Comment by frankie567** [comment]
Hi @YaraslauZhylko 👋 

Yep, definitely a bug on our side! Actually, `ASGIWebSocketTransport` "emulates" an ASGI server so we need to make sure all the data is correctly passed in `scope`, including `subprotocols`.

**Comment by YaraslauZhylko** [comment]
Checked it im pur project.
The fix works perfectly.
Thank you.
