### ISSUE TITLE
Newest anyio 4 has moved start_blocking_portal context manager to from_thread module

### ISSUE THREAD

**Issue by maparent** [frankie567/httpx-ws#47]
## Describe the bug

When upgrading anyio to version 4, all tests (but one) in tests/test_transport.py fail with `AttributeError: module 'anyio' has no attribute 'start_blocking_portal'`
There is a call to `anyio.start_blocking_portal` at `transport.py:46`.
This should be replaced by `anyio.from_thread.start_blocking_portal`, which is also compatible with `anyio==3.7.1`

## To Reproduce

Run tests

## Expected behavior

Tests pass

## Configuration

 - Python version: 3.10, 3.11
 - httpx-ws version: git main head (31b6683b80d0a4d8cce5f78fd6bf23e209d6360e)

**Comment by frankie567** [comment]
Good catch, thanks 🙏

PR welcome for this fix!
