### ISSUE TITLE
connect_ws and aconnect_ws always raise WebSocketNetworkError when keepalive_ping_timeout_seconds + keepalive_ping_interval_seconds

### ISSUE THREAD

**Issue by lee-cq** [frankie567/httpx-ws#50]
## connect_ws and aconnect_ws always raise WebSocketNetworkError when keepalive_ping_timeout_seconds + keepalive_ping_interval_seconds (Actual WS is working normally)

![image](https://github.com/frankie567/httpx-ws/assets/47050568/977488c0-ed95-465c-8f77-02f122282997)
![image](https://github.com/frankie567/httpx-ws/assets/47050568/2fb89448-ef79-42f2-82e5-62eab5414e03)

## To Reproduce

```python
try:
    with Client(base_url=url, params={'token': token}) as client:
        with connect_ws('/traffic', client,
                        keepalive_ping_timeout_seconds=3,
                        keepalive_ping_interval_seconds=4
                        ) as ws:
            n = 0
            start = time.time()
            while True:
                n += 1
                print(n, ws.receive_json())
except WebSocketNetworkError:
    print('WebSocketNetworkError, total time:', time.time() - start)
```

## Expected behavior

The server sends traffic once per second, which is stable and permanent, and should not trigger errors or timeouts

## Configuration
 - Python version: 3.11.4
 - httpx-ws version: 0.4.1
 - httpx version: 0.24.1

## Additional context

None

**Comment by frankie567** [comment]
How and with what libraries is your WebSocket server implemented? It looks to me that it doesn't answer the ping request. The client expects a specific answer to its ping, it doesn't consider other messages.

**Comment by lee-cq** [comment]
Thank you very much for your reply.

The service is clash premium, and I'll check to see if it responds to ping requests.

My current solution is to set keepalive_ping_timeout_seconds to None.
