### ISSUE TITLE
option to not use the blocking portal

### ISSUE THREAD

**Issue by zsorizs** [frankie567/httpx-ws#72]
## Describe the bug

In our use, it is important to run the tested app in the same event loop as the testing fixtures.

(Basically we preinitialise stuff for the app and that happens in the event loop supplied by pytest. Then we need to keep everything on this loop so that cleanup works correctly. We have run into issues when doing this with redis or database connections).

## Expected behavior

Replacing the blocking portal with asyncio.create_task fixes the issues for us.

Making the blocking portal optional could be the solution that works for everyone.

Here is a patch that does that:
[optional.blocking.portal.patch](https://github.com/user-attachments/files/16069192/optional.blocking.portal.patch)

## Configuration
 - Python version: 3.11
 - httpx-ws version: 0.6

**Comment by subetechx** [comment]
Upvoting this patch, it fixed my issue with database connection, thanks!

**Comment by frankie567** [comment]
Thank you for this @zsorizs 👍 

Actually, I would be even interested by dropping the blocking portal completely; and always use your version that use `TaskGroup`. Fell free to open a PR!

**Comment by agronholm** [comment]
That version will not work on any Python version lower than 3.12, which I doubt is acceptable here. The only way it can work is by using AnyIO's task groups.

**Comment by agronholm** [comment]
Furthermore, the patch does not do anything about its use of synchronous queues, so any reads from an empty queue or writes to a full queue will block the event loop.

**Comment by RoyLeviLangware** [comment]
Reviving the conversation here as we also have this issue an unexpected new event loop in the websocket endpoint while testing.
I already found 2 forks addressing this and don't really wish to be the 3rd :)
Any new thoughts or advice?

**Comment by frankie567** [comment]
> I already found 2 forks addressing this and don't really wish to be the 3rd :)

As mentioned, would be happy to review a PR solving this, but still waiting 🤷
